#!/bin/bash

chmod +x /lib/security/pam_oauth2_device.so

chmod +x /etc/nginx/bin/update_pam_com.sh
chmod +x /etc/nginx/bin/update_pam_uncom.sh
ln -s /etc/nginx/sites-available/qrauthent.conf /etc/nginx/sites-enabled/qrauthent.conf
systemctl restart nginx

chmod +x /usr/share/web-greeter/themes/qrauthent
systemctl restart lightdm

echo -e "\nLe programme d'authentification par QRcode a bien été installé !\nVeuillez redémarrer la machine via la commande suivante :\n\tsudo shutdown -h now\n\n À bientôt."

