#!/bin/bash -x


COLOR="\e[92m"
NO_COLOR="\e[0m"

echo -e "\n${COLOR}Démarrage de la post-installation...${NO_COLOR}\n"

echo -e "\n${COLOR}Configuration de PAM.${NO_COLOR}\n"
chmod +x /lib/security/pam_oauth2_device.so

echo -e "\n${COLOR}Configuration du serveur WEB.${NO_COLOR}\n"
chmod +x /etc/nginx/bin/update_pam_com.sh
chmod +x /etc/nginx/bin/update_pam_uncom.sh
ln -s /etc/nginx/sites-available/qrauthent.conf /etc/nginx/sites-enabled/qrauthent.conf
systemctl restart nginx

echo -e "\n${COLOR}Configuration de Lightdm.${NO_COLOR}\n"
chmod +x /usr/share/web-greeter/themes/qrauthent
systemctl restart lightdm

echo -e "\n${COLOR}Le programme d'authentification par QRcode a bien été installé !\nVeuillez redémarrer la machine via la commande suivante :\n\tsudo shutdown -h now\n\n À bientôt.${NO_COLOR}"

